apiVersion: v1
kind: Pod
metadata:
  name: gpu-monitor
  labels:
    name: gpu-monitor
spec:
  nodeSelector:
    hardware-type: CPUONLY
  restartPolicy: Always
  containers:
    - name: nginx
      image: ic-registry.epfl.ch/mlo/gpu-monitor-nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /mlodata1
          name: mlodata1
    - name: php
      image: ic-registry.epfl.ch/mlo/gpu-monitor-php:latest
      volumeMounts:
        - mountPath: /mlodata1
          name: mlodata1
  volumes:
    - name: mlo-scratch
      persistentVolumeClaim:
        claimName: mlo-scratch
    - name: mlodata1
      persistentVolumeClaim:
        claimName: pv-mlodata1
