apiVersion: v1
kind: Service
metadata:
  name: gpu-monitor
  labels:
    user: cordonni
spec:
  type: NodePort
  ports:
  - name: http
    targetPort: 8080
    port: 8080
    nodePort: 30999
    protocol: TCP
  selector:
    name: gpu-monitor
